'use strict';

// Shared path resolution for the §42 test suites.
//
// Nothing here may hard-code a machine. Two of the four suites need things that
// live outside this repo — the generated catalogue on OneDrive, and the Console
// checkout — so both are located rather than assumed, and a suite that cannot
// find what it needs says so and skips rather than failing as though the code
// were broken.

const fs = require('fs');
const path = require('path');
const os = require('os');

const REPO = path.resolve(__dirname, '..', '..');

// The canonical reducer. Everything else is a mirror of this file.
const REDUCER = path.join(REPO, 'utils', 'procurement-reduce.js');

// `--flag value` or `--flag=value`, so the suites can be pointed anywhere.
function arg(name) {
  const argv = process.argv.slice(2);
  const eq = argv.find(a => a.startsWith('--' + name + '='));
  if (eq) return eq.slice(name.length + 3);
  const i = argv.indexOf('--' + name);
  if (i !== -1 && argv[i + 1]) return argv[i + 1];
  return null;
}

// The catalogue is generated by tools/build-procurement-catalogue.py into the
// IDMS OneDrive folder, whose name carries the tenant ("OneDrive - O'Hara
// Corporation") and so cannot be spelled out here.
function findCatalogue() {
  const explicit = arg('catalogue') || process.env.IDMS_CATALOGUE;
  if (explicit) return fs.existsSync(explicit) ? explicit : null;
  const home = os.homedir();
  let entries = [];
  try { entries = fs.readdirSync(home); } catch (_) { return null; }
  for (const e of entries) {
    if (!e.startsWith('OneDrive')) continue;
    const p = path.join(home, e, 'Documents', 'IDMS', 'data', 'procurement', 'catalogue.json');
    if (fs.existsSync(p)) return p;
  }
  return null;
}

// The Console checkout, for the cross-repo contract suite. An explicitly given
// path is used or refused — never quietly swapped for the default, which would
// report a pass against a checkout the caller did not mean.
function findConsole() {
  const explicit = arg('console') || process.env.IDMS_CONSOLE;
  const looksRight = c => fs.existsSync(path.join(c, 'src', 'main', 'main.js'));
  if (explicit) return looksRight(explicit) ? explicit : null;
  const beside = path.resolve(REPO, '..', 'IDMS-Console');
  return looksRight(beside) ? beside : null;
}

// Counters shared by every suite, so the runner can total them.
function counter() {
  const state = { ok: 0, bad: 0 };
  state.check = function (label, got, want) {
    const pass = (arguments.length === 2) ? !!got : JSON.stringify(got) === JSON.stringify(want);
    if (pass) { state.ok++; console.log('  ok   ' + label); }
    else {
      state.bad++;
      console.log('  FAIL ' + label +
        (arguments.length === 2 ? '' :
          '\n       got  ' + JSON.stringify(got) + '\n       want ' + JSON.stringify(want)));
    }
  };
  state.note = msg => console.log('  ..   ' + msg);
  state.head = msg => console.log('\n' + msg);
  state.done = function () {
    console.log('\n' + state.ok + ' passed, ' + state.bad + ' failed');
    return state.bad === 0;
  };
  return state;
}

function skip(reason) {
  console.log('\nSKIPPED — ' + reason);
  process.exit(0);
}

module.exports = { REPO, REDUCER, arg, findCatalogue, findConsole, counter, skip };
